name: 2d_classif

savedir: results
dataset: 2d_classif
n_runs: 1
n_jobs: null
n_estimators: 1
epochs: 500
batch_size: 32
steps_per_epoch: 100
network: DenseNet
network_params:
    layers: 3
    last_units: 1
    activation: "relu"
    last_activation: null
optimizer: Adam
optimizer_params:
    lr: 0.001
loss: BinaryCrossentropy
metrics: [acc]
callbacks: SaveModel
callbacks_params:
    monitor: acc